-- TABLE 1
 CREATE TABLE IF NOT EXISTS T15_CUSTOMER
(
	T15_CUST_ID INTEGER NOT NULL ,
	T15_CUST_FNAME VARCHAR(10) NOT NULL ,
	T15_CUST_LNAME VARCHAR(10) NOT NULL ,
	T15_CUST_DOB DATE NOT NULL ,
	T15_CUST_GENDER CHAR(2) NOT NULL ,
	T15_CUST_ADDRESS VARCHAR(20) NOT NULL ,
	T15_CUST_MOB_NUMBER VARCHAR(10) NOT NULL ,
	T15_CUST_EMAIL VARCHAR(20) NOT NULL ,
    T15_CUST_PASSPORT_NUMBER VARCHAR(20) NOT NULL ,
    T15_CUST_MARITAL_STATUS CHAR(10) NOT NULL ,
	T15_CUST_PPS_NUMBER INTEGER NOT NULL ,
    CONSTRAINT T15_XPKCUSTOMER_1 PRIMARY KEY (T15_CUST_ID)
);



-- TABLE 2
CREATE TABLE IF NOT EXISTS T15_INCIDENT
(
	T15_INCIDENT_ID VARCHAR(20) NOT NULL ,
	T15_INCIDENT_TYPE VARCHAR(30) NOT NULL ,
	T15_INCIDENT_DATE DATE NOT NULL ,
	T15_DESCRIPTION VARCHAR(100) NOT NULL ,
	CONSTRAINT T15_XPKINCIDENT_17 PRIMARY KEY (T15_INCIDENT_ID)
);



-- TABLE 3
CREATE TABLE IF NOT EXISTS T15_INCIDENT_REPORT
(
	T15_INCIDENT_REPORT_ID VARCHAR(20) NOT NULL  ,
	T15_INCIDENT_TYPE CHAR(10) NOT NULL ,
	T15_INCIDENT_INSPECTOR VARCHAR(20) NOT NULL ,
	T15_INCIDENT_COST INTEGER NOT NULL ,
	T15_INCIDENT_REPORT_DESCRIPTION VARCHAR(100) NOT NULL ,
    T15_INCIDENT_ID VARCHAR(20) NOT NULL ,
    T15_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T15_XPKINCIDENT_REPORT_18 PRIMARY KEY (T15_INCIDENT_REPORT_ID),
	CONSTRAINT T15_R_83 FOREIGN KEY (T15_INCIDENT_ID) REFERENCES T15_INCIDENT(T15_INCIDENT_ID) ON DELETE CASCADE,
	CONSTRAINT T15_R_86 FOREIGN KEY (T15_CUST_ID) REFERENCES T15_CUSTOMER(T15_CUST_ID) ON DELETE CASCADE
);



-- TABLE 4
CREATE TABLE IF NOT EXISTS T15_INSURANCE_COMPANY
(
	T15_COMPANY_NAME VARCHAR(20) NOT NULL ,
	T15_COMPANY_ADDRESS VARCHAR(20) NOT NULL ,
	T15_COMPANY_CONTACT_NUMBER VARCHAR(10) NOT NULL ,
	T15_COMPANY_FAX INTEGER NOT NULL ,
	T15_COMPANY_EMAIL VARCHAR(20) NOT NULL ,
	T15_COMPANY_WEBSITE VARCHAR(20) NOT NULL ,
	T15_COMPANY_LOCATION VARCHAR(20) NOT NULL ,
    T15_COMPANY_DEPARTMENT_NAME VARCHAR(20) NOT NULL ,
	T15_COMPANY_OFFICE_NAME VARCHAR(20) NOT NULL ,
	CONSTRAINT T15_XPKINSURANCE_COMPANY_15 PRIMARY KEY(T15_COMPANY_NAME,T15_COMPANY_DEPARTMENT_NAME)
);


-- TABLE 5
CREATE TABLE IF NOT EXISTS T15_DEPARTMENT
(
	T15_DEPARTMENT_NAME VARCHAR(20) NOT NULL ,
	T15_COMPANY_NAME VARCHAR(20) NOT NULL ,
	T15_OFFICE VARCHAR(18) NOT NULL ,
	T15_CONTACT_INFORMATION VARCHAR(30) NOT NULL,
	T15_DEPARTMENT_STAFF VARCHAR(18) NOT NULL ,
	T15_DEPARTMENT_LEADER VARCHAR(18) NOT NULL ,
	CONSTRAINT T15_XPKDEPARTMENT PRIMARY KEY (T15_DEPARTMENT_NAME),
	CONSTRAINT T15_R_56 FOREIGN KEY (T15_COMPANY_NAME,T15_DEPARTMENT_NAME) REFERENCES T15_INSURANCE_COMPANY (T15_COMPANY_NAME,T15_COMPANY_DEPARTMENT_NAME) ON UPDATE CASCADE
);



-- TABLE 6
CREATE TABLE IF NOT EXISTS T15_VEHICLE
(
	T15_VEHICLE_ID INTEGER NOT NULL ,
	T15_POLICY_ID VARCHAR(20) NOT NULL ,
	T15_DEPENDENT_NOK_ID VARCHAR(20) NOT NULL ,
	T15_VEHICLE_REGISTRATION_NUMBER VARCHAR(20) NOT NULL ,
	T15_VEHICLE_VALUE INTEGER NOT NULL ,
	T15_VEHICLE_TYPE VARCHAR(20) NOT NULL ,
	T15_VEHICLE_SIZE INTEGER NOT NULL ,
	T15_VEHICLE_NUMBER_OF_SEAT INTEGER NOT NULL ,
	T15_VEHICLE_MANUFACTURER VARCHAR(20) NOT NULL ,
	T15_VEHICLE_ENGINE_NUMBER INTEGER NOT NULL ,
	T15_VEHICLE_CHASIS_NUMBER INTEGER NOT NULL ,
	T15_VEHICLE_NUMBER VARCHAR(20) NOT NULL ,
	T15_VEHICLE_MODEL_NUMBER VARCHAR(20) NOT NULL ,
	T15_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T15_XPKVEHICLE_6 PRIMARY KEY (T15_VEHICLE_ID),
	CONSTRAINT T15_R_92 FOREIGN KEY (T15_CUST_ID) REFERENCES T15_CUSTOMER(T15_CUST_ID) ON DELETE CASCADE
);




-- TABLE 7
CREATE TABLE IF NOT EXISTS T15_VEHICLE_SERVICE
(
	T15_VEHICLE_SERVICE VARCHAR(30) NOT NULL ,
	T15_VEHICLE_ID INTEGER NOT NULL ,
	T15_CUST_ID INTEGER NOT NULL ,
	T15_DEPARTMENT_NAME VARCHAR(20) NOT NULL ,
	T15_VEHICLE_SERVICE_ADDRESS VARCHAR(20) NOT NULL ,
	T15_VEHICLE_SERVICE_CONTACT VARCHAR(20) NOT NULL ,
	T15_VEHICLE_SERVICE_INCHARGE VARCHAR(20) NOT NULL ,
	T15_VEHICLE_SERVICE_TYPE VARCHAR(20) NOT NULL ,
	T15_COMPANY_NAME VARCHAR(20) NOT NULL ,
	CONSTRAINT T15_XPKVEHICLE_SERVICE PRIMARY KEY(T15_VEHICLE_SERVICE),
	CONSTRAINT T15_R_50 FOREIGN KEY (T15_VEHICLE_ID) REFERENCES T15_VEHICLE(T15_VEHICLE_ID) ON DELETE CASCADE,
	CONSTRAINT T15_R_51 FOREIGN KEY (T15_CUST_ID) REFERENCES T15_CUSTOMER(T15_CUST_ID) ON DELETE RESTRICT 
);



-- TABLE 8
CREATE TABLE IF NOT EXISTS T15_PREMIUM_PAYMENT
(
	T15_PREMIUM_PAYMENT_ID VARCHAR(20) NOT NULL ,
	T15_POLICY_NUMBER VARCHAR(20) NOT NULL ,
	T15_PREMIUM_PAYMENT_AMOUNT INTEGER NOT NULL DEFAULT 0 ,
	T15_PREMIUM_PAYMENT_SCHEDULE DATE NOT NULL ,
	T15_RECEIPT_ID VARCHAR(20) NOT NULL ,
	T15_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T15_XPKPREMIUM_PAYMENT_5 PRIMARY KEY(T15_PREMIUM_PAYMENT_ID),
	CONSTRAINT T15_R_85 FOREIGN KEY (T15_CUST_ID) REFERENCES T15_CUSTOMER(T15_CUST_ID) ON DELETE CASCADE
);




-- TABLE 9
CREATE TABLE IF NOT EXISTS T15_RECEIPT
(
	T15_RECEIPT_ID VARCHAR(20) NOT NULL ,
	T15_TIME DATE NOT NULL ,
	T15_COST INTEGER NOT NULL ,
	T15_PREMIUM_PAYMENT_ID VARCHAR(20) NOT NULL ,
	T15_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T15_XPKRECEIPT_21 PRIMARY KEY(T15_RECEIPT_ID),
	CONSTRAINT T15_R_84 FOREIGN KEY (T15_PREMIUM_PAYMENT_ID) REFERENCES T15_PREMIUM_PAYMENT (T15_PREMIUM_PAYMENT_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT T15_R_88 FOREIGN KEY (T15_CUST_ID) REFERENCES T15_CUSTOMER ( T15_CUST_ID) ON UPDATE RESTRICT ON DELETE CASCADE
);


-- TABLE 10
CREATE TABLE IF NOT EXISTS T15_APPLICATION
(
	T15_APPLICATION_ID VARCHAR(20) NOT NULL ,
	T15_VEHICLE_ID INTEGER NOT NULL ,
	T15_APPLICATION_STATUS CHAR(8) NOT NULL ,
	T15_COVERAGE VARCHAR(50) NOT NULL ,
	T15_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T15_XPKAPPLICATION_2 PRIMARY KEY(T15_APPLICATION_ID),
	CONSTRAINT T15_R_93 FOREIGN KEY (T15_CUST_ID) REFERENCES T15_CUSTOMER(T15_CUST_ID) ON UPDATE RESTRICT
);


-- TABLE 11
CREATE TABLE IF NOT EXISTS  T15_INSURANCE_POLICY
(
	T15_AGREEMENT_ID VARCHAR(20) NOT NULL ,
	T15_DEPARTMENT_NAME VARCHAR(20) NOT NULL ,
	T15_POLICY_NUMBER VARCHAR(20) NOT NULL ,
	T15_START_DATE DATE NOT NULL ,
	T15_EXPIRY_DATE DATE NOT NULL ,
	T15_TERM_CONDITION_DESCRIPTION VARCHAR(100) NOT NULL ,
	T15_APPLICATION_ID VARCHAR(20) NOT NULL ,
	T15_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T15_XPKINSURANCE_POLICY_4 PRIMARY KEY(T15_AGREEMENT_ID),
	CONSTRAINT T15_R_95 FOREIGN KEY (T15_APPLICATION_ID) REFERENCES T15_APPLICATION (T15_APPLICATION_ID) ON DELETE CASCADE ,
    CONSTRAINT T15_R_96 FOREIGN KEY (T15_CUST_ID) REFERENCES T15_CUSTOMER (T15_CUST_ID) ON UPDATE RESTRICT
    
);



-- TABLE 12
CREATE TABLE IF NOT EXISTS T15_POLICY_RENEWABLE
(
	T15_POLICY_RENEWABLE_ID VARCHAR(20) NOT NULL ,
	T15_DATE_OF_RENEWAL DATE NOT NULL ,
	T15_TYPE_OF_RENEWAL CHAR(15) NOT NULL ,
	T15_AGREEMENT_ID VARCHAR(20) NOT NULL ,
	T15_APPLICATION_ID VARCHAR(20) NOT NULL ,
	T15_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T15_XPKPOLICY_RENEWABLE_16 PRIMARY KEY(T15_POLICY_RENEWABLE_ID),
	CONSTRAINT T15_R_101 FOREIGN KEY (T15_AGREEMENT_ID)REFERENCES T15_INSURANCE_POLICY (T15_AGREEMENT_ID) ON DELETE CASCADE,
    CONSTRAINT T15_R_102 FOREIGN KEY (T15_APPLICATION_ID)REFERENCES T15_APPLICATION(T15_APPLICATION_ID) ON UPDATE CASCADE,
    CONSTRAINT T15_R_103 FOREIGN KEY (T15_CUST_ID)REFERENCES T15_CUSTOMER (T15_CUST_ID) ON UPDATE RESTRICT
);



-- TABLE 13
CREATE TABLE IF NOT EXISTS T15_MEMBERSHIP
(
	T15_MEMBERSHIP_ID VARCHAR(20) NOT NULL ,
	T15_MEMBERSHIP_TYPE CHAR(15) NOT NULL ,
	T15_ORGANISATION_CONTACT VARCHAR(20) NOT NULL ,
	T15_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T15_XPKMEMBERSHIP_12 PRIMARY KEY(T15_MEMBERSHIP_ID),
	CONSTRAINT T15_R_91 FOREIGN KEY (T15_CUST_ID) REFERENCES T15_CUSTOMER(T15_CUST_ID) ON DELETE CASCADE
);



-- TABLE 14
CREATE TABLE IF NOT EXISTS T15_QUOTE
(
	T15_QUOTE_ID VARCHAR(20) NOT NULL ,
	T15_ISSUE_DATE DATE NOT NULL ,
	T15_VALID_FROM_DATE DATE NOT NULL ,
	T15_VALID_TILL_DATE DATE NOT NULL ,
	T15_DESCRIPTION VARCHAR(100) NOT NULL ,
	T15_PRODUCT_ID VARCHAR(20) NOT NULL ,
	T15_COVERAGE_LEVEL VARCHAR(20) NOT NULL ,
	T15_APPLICATION_ID VARCHAR(20) NOT NULL ,
	T15_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T15_XPKQU0TE_3 PRIMARY KEY (T15_QUOTE_ID),
	CONSTRAINT T15_R_71 FOREIGN KEY (T15_APPLICATION_ID) REFERENCES T15_APPLICATION (T15_APPLICATION_ID) ON DELETE CASCADE,
	CONSTRAINT T15_R_72 FOREIGN KEY (T15_CUST_ID) REFERENCES T15_CUSTOMER(T15_CUST_ID) ON DELETE CASCADE 
);


-- TABLE 15
CREATE TABLE IF NOT EXISTS T15_STAFF
(
	T15_STAFF_ID VARCHAR(20) NOT NULL ,
	T15_STAFF_FNAME VARCHAR(10) NOT NULL ,
	T15_STAFF_LNAME VARCHAR(10) NOT NULL ,
	T15_STAFF_ADDRESS VARCHAR(20) NOT NULL ,
	T15_STAFF_CONTACT VARCHAR(10) NOT NULL ,
	T15_STAFF_GENDER CHAR(2) NOT NULL ,
	T15_STAFF_MARITAL_STATUS CHAR(10) NOT NULL ,
	T15_STAFF_NATIONALITY CHAR(15) NOT NULL ,
	T15_STAFF_QUALIFICATION VARCHAR(20) NOT NULL ,
	T15_STAFF_ALLOWANCE INTEGER NOT NULL ,
	T15_STAFF_PPS_NUMBER INTEGER NOT NULL ,
	T15_COMPANY_NAME VARCHAR(20) NOT NULL ,
	CONSTRAINT T15_XPKSTAFF_9 PRIMARY KEY (T15_STAFF_ID),
	CONSTRAINT T15_R_105 FOREIGN KEY (T15_COMPANY_NAME) REFERENCES T15_INSURANCE_COMPANY (T15_COMPANY_NAME) ON UPDATE CASCADE
);



-- TABLE 16
CREATE TABLE IF NOT EXISTS T15_NOK
(
   T15_NOK_ID VARCHAR(20) NOT NULL ,
   T15_NOK_NAME VARCHAR(20) NOT NULL ,
   T15_NOK_ADDRESS VARCHAR(20) NOT NULL , 
   T15_NOK_PHONE_NUMBER VARCHAR(10) NOT NULL ,
   T15_NOK_GENDER CHAR(2) NOT NULL ,
   T15_NOK_MARITAL_STATUS CHAR(10) NOT NULL ,
   T15_AGREEMENT_ID VARCHAR(20) NOT NULL ,
   T15_APPLICATION_ID VARCHAR(20) NOT NULL ,
   T15_CUST_ID INTEGER NOT NULL ,
   CONSTRAINT T15_XPKNOK_14 PRIMARY KEY (T15_NOK_ID),
   CONSTRAINT R_73 FOREIGN KEY (T15_AGREEMENT_ID) REFERENCES T15_INSURANCE_POLICY (T15_AGREEMENT_ID) ON DELETE CASCADE,
   CONSTRAINT R_74 FOREIGN KEY ( T15_APPLICATION_ID) REFERENCES T15_APPLICATION(T15_APPLICATION_ID) ON DELETE CASCADE,
   CONSTRAINT R_75 FOREIGN KEY (T15_CUST_ID) REFERENCES T15_CUSTOMER(T15_CUST_ID) ON UPDATE RESTRICT ON DELETE CASCADE
);



-- TABLE 17
CREATE TABLE IF NOT EXISTS T15_PRODUCT 
( 
	T15_PRODUCT_PRICE INTEGER NOT NULL ,
	T15_PRODUCT_TYPE CHAR(15) NOT NULL , 
	T15_PRODUCT_NUMBER VARCHAR(20) NOT NULL ,
	T15_COMPANY_NAME VARCHAR(20) NOT NULL ,
	CONSTRAINT T15_XPKPRODUCT_20 PRIMARY KEY (T15_PRODUCT_NUMBER), 
	CONSTRAINT T15_R_107 FOREIGN KEY (T15_COMPANY_NAME) REFERENCES T15_INSURANCE_COMPANY (T15_COMPANY_NAME) ON UPDATE CASCADE
);





-- TABLE 18
CREATE TABLE IF NOT EXISTS T15_OFFICE 
( 
	T15_OFFICE_NAME VARCHAR(20) NOT NULL , 
	T15_OFFICE_LEADER VARCHAR(20) NOT NULL , 
	T15_CONTACT_INFORMATION VARCHAR(20) NOT NULL , 
	T15_ADDRESS VARCHAR(20) NOT NULL ,
	T15_ADMIN_COST INTEGER NOT NULL , 
	T15_STAFF VARCHAR(50) NOT NULL , 
	T15_DEPARTMENT_NAME VARCHAR(20) NOT NULL , 
	T15_COMPANY_NAME VARCHAR(20) NOT NULL , 
	CONSTRAINT T15_XPKOFFICE_11 PRIMARY KEY (T15_OFFICE_NAME), 
	CONSTRAINT T15_R_110 FOREIGN KEY (T15_DEPARTMENT_NAME) REFERENCES T15_DEPARTMENT (T15_DEPARTMENT_NAME) ON DELETE CASCADE,
    CONSTRAINT T15_R_111 FOREIGN KEY (T15_COMPANY_NAME) REFERENCES T15_INSURANCE_COMPANY (T15_COMPANY_NAME) ON UPDATE CASCADE
);


 
-- TABLE 19
CREATE TABLE IF NOT EXISTS T15_COVERAGE
(
	T15_COVERAGE_ID VARCHAR(20) NOT NULL ,
	T15_COVERAGE_AMOUNT INTEGER NOT NULL ,
	T15_COVERAGE_TYPE CHAR(10) NOT NULL ,
	T15_COVERAGE_LEVEL CHAR(15) NOT NULL ,
	T15_PRODUCT_ID VARCHAR(20) NOT NULL ,
	T15_COVERAGE_DESCRIPTION VARCHAR(100) NOT NULL ,
	T15_COVEARGE_TERMS VARCHAR(50)  NOT NULL ,
	T15_COMPANY_NAME VARCHAR(20) NOT NULL ,
	CONSTRAINT T15_XPKCOVERAGE_19 PRIMARY KEY (T15_COVERAGE_ID),
	CONSTRAINT T15_R_112 FOREIGN KEY (T15_COMPANY_NAME) REFERENCES T15_INSURANCE_COMPANY (T15_COMPANY_NAME) ON UPDATE CASCADE
);


-- TABLE 20
CREATE TABLE IF NOT EXISTS T15_INSURANCE_POLICY_COVERAGE
(
	T15_AGREEMENT_ID VARCHAR(20) NOT NULL ,
	T15_COVERAGE_ID VARCHAR(20)NOT NULL ,
	CONSTRAINT T15_XPKINSURANCE_POLICY_4 PRIMARY KEY(T15_AGREEMENT_ID),
	CONSTRAINT T15_R_98 FOREIGN KEY (T15_COVERAGE_ID)REFERENCES T15_COVERAGE(T15_COVERAGE_ID) ON DELETE CASCADE
);





-- TABLE 21
CREATE TABLE IF NOT EXISTS T15_CLAIM 
( 
	T15_CLAIM_ID INTEGER NOT NULL ,
	T15_AGREEMENT_ID VARCHAR(20) NOT NULL , 
	T15_CLAIM_AMOUNT INTEGER NOT NULL , 
	T15_INCIDENT_ID VARCHAR(20) NOT NULL , 
	T15_DAMAGE_TYPE VARCHAR(20) NOT NULL , 
	T15_DATE_OF_CLAIM DATE NOT NULL ,
	T15_CLAIM_STATUS CHAR(10) NOT NULL ,
	T15_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T15_XPKCLAIM_7 PRIMARY KEY (T15_CLAIM_ID),
	CONSTRAINT T15_R_115 FOREIGN KEY (T15_CUST_ID) REFERENCES T15_CUSTOMER(T15_CUST_ID) ON UPDATE RESTRICT
);



-- TABLE 22
CREATE TABLE IF NOT EXISTS T15_CLAIM_SETTLEMENT
(
	T15_CLAIM_SETTLEMENT_ID INTEGER NOT NULL ,
	T15_VEHICLE_ID INTEGER NOT NULL ,
	T15_DATE_SETTLED DATE NOT NULL ,
	T15_AMOUNT_PAID INTEGER NOT NULL ,
	T15_COVERAGE_ID VARCHAR(20) NOT NULL ,
	T15_CLAIM_ID INTEGER NOT NULL ,
	T15_CUST_ID INTEGER NOT NULL ,
	CONSTRAINT T15_XPKCLAIM_SETTLEMENT_8 PRIMARY KEY(T15_CLAIM_SETTLEMENT_ID),
	CONSTRAINT T15_R_120 FOREIGN KEY (T15_CLAIM_ID) REFERENCES T15_CLAIM(T15_CLAIM_ID) ON DELETE CASCADE,
	CONSTRAINT T15_R_121 FOREIGN KEY (T15_CUST_ID) REFERENCES T15_CUSTOMER(T15_CUST_ID) ON DELETE CASCADE
);

