
-- Query 1
SELECT 
    *
FROM
    T15_CUSTOMER C,
    T15_VEHICLE V
WHERE
    V.T15_CUST_ID = C.T15_CUST_ID
        AND C.T15_CUST_ID IN (SELECT 
            C1.T15_CUST_ID
        FROM
            T15_CLAIM C1
        WHERE
            C1.T15_CLAIM_STATUS = 'PENDING'
                AND C1.T15_INCIDENT_ID IN (SELECT 
                    I.T15_INCIDENT_ID
                FROM
                    T15_INCIDENT_REPORT I
                WHERE
                    I.T15_CUST_ID = C1.T15_CUST_ID));

-- Query 2    
SELECT 
    *
FROM
    T15_CUSTOMER C
WHERE
    C.T15_CUST_ID IN (SELECT 
            P.T15_CUST_ID
        FROM
            T15_PREMIUM_PAYMENT P
        WHERE
            P.T15_CUST_ID = C.T15_CUST_ID
                AND P.T15_PREMIUM_PAYMENT_AMOUNT > (SELECT 
                    SUM(T15_CUST_ID)
                FROM
                    T15_CUSTOMER));

    
-- Query 3 Revamped


SELECT DISTINCT
    (T15_COMPANY_NAME)
FROM
    T15_INSURANCE_COMPANY
WHERE
    T15_COMPANY_NAME IN 
		(
            -- 1st condition
			SELECT 
				P.T15_COMPANY_NAME
			FROM
				T15_PRODUCT P
					INNER JOIN
				t15_department D ON P.T15_COMPANY_NAME = D.T15_COMPANY_NAME
			GROUP BY P.T15_COMPANY_NAME
			HAVING COUNT(DISTINCT (T15_PRODUCT_NUMBER)) > COUNT(DISTINCT (T15_DEPARTMENT_NAME))
        )
        AND T15_COMPANY_NAME IN 
        (
            -- 2nd condition
			SELECT 
				T15_COMPANY_NAME
			FROM
				T15_INSURANCE_COMPANY
			GROUP BY T15_COMPANY_NAME
			HAVING COUNT(DISTINCT (T15_COMPANY_LOCATION)) > 1
        );











-- Query 4
SELECT 
    C.*
FROM
    (((T15_CUSTOMER C
    INNER JOIN T15_VEHICLE V ON (C.T15_CUST_ID = V.T15_CUST_ID))
    INNER JOIN T15_PREMIUM_PAYMENT P ON (P.T15_CUST_ID = V.T15_CUST_ID
        AND P.T15_PREMIUM_PAYMENT_AMOUNT = 0))
    INNER JOIN T15_INCIDENT_REPORT IR ON (IR.T15_CUST_ID = P.T15_CUST_ID
        AND IR.T15_INCIDENT_TYPE = 'ACCIDENT'))
GROUP BY V.T15_CUST_ID
HAVING COUNT(V.T15_VEHICLE_ID) > 1;



-- Query 5
SELECT DISTINCT
    V.*
FROM
    T15_VEHICLE V,
    T15_PREMIUM_PAYMENT P
WHERE
    V.T15_CUST_ID = P.T15_CUST_ID
        AND P.T15_PREMIUM_PAYMENT_AMOUNT > V.T15_VEHICLE_NUMBER;


-- Query 6
SELECT 
    C.*
FROM
    (T15_CUSTOMER C
    INNER JOIN T15_CLAIM_SETTLEMENT CS ON CS.T15_CUST_ID = C.T15_CUST_ID
    INNER JOIN T15_CLAIM CL ON (CL.T15_CLAIM_ID = CS.T15_CLAIM_ID)
    INNER JOIN T15_COVERAGE CO ON (CO.T15_COVERAGE_ID = CS.T15_COVERAGE_ID
        AND CL.T15_CLAIM_AMOUNT < CO.T15_COVERAGE_AMOUNT
        AND CL.T15_CLAIM_AMOUNT > (CS.T15_CLAIM_SETTLEMENT_ID + CS.T15_VEHICLE_ID + CS.T15_CLAIM_ID + CS.T15_CUST_ID)));
    
